algorithm: glocalmatch
save_dir: ./saved_models/opendomain_cv
save_name: glocalmatch_visda_r150_0
resume: True
load_path: ./saved_models/opendomain_cv/glocalmatch_visda_r150_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 5
num_train_iter: 5120
num_eval_iter: 1024
num_log_iter: 256
num_labels: 150
labeled_domain: real
unlabeled_domain: synthetic
single_base: False
batch_size: 64
eval_batch_size: 256
p_cutoff: 0.95
cluster_loss_ratio: 1.0
ulb_loss_ratio: 1.0
T: 0.2
proj_size: 128
smoothing_alpha: 0.9
cluster_scale: 100
min_cluster: 0.9
da_len: 32
use_da: True
uratio: 1
ema_m: 0.999
use_ema_bank: False
ema_bank_m: 0.7
crop_ratio: 0.875
img_size: 96
optim: SGD
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
dataset: visda
train_sampler: RandomSampler
num_classes: 6
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: None
